### ISSUE TITLE
Is this mod still worked on/given support for?

### ISSUE THREAD

**Issue by Duranson1** [mineLdiver/smoothbeta#4]
Hi there,

Your mod improves my frames drastically on my windows PC, but unfortunately on my macbook I deal with the same shader issues another issue discussed. But I notice the months-old issue doesn't contain responses, and the mod hasn't been updated in awhile, are there any plans for future updates? thanks :)

**Comment by mineLdiver** [comment]
I'm aware of most of the issues, alas, the mod's development is paused for the time being so I can focus on finishing my bachelor's and releasing StationAPI 2.0 instead, which almost all of the Babric ecosystem relies on, including SmoothBeta.

**Comment by Duranson1** [comment]
Gotcha, good luck on your bachelors and statapi! appreciate the work you do for the b1.7.3 babric modding scene.
